################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    build: .
    image: picroscope-hub-node-red:latest
    restart: always
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    devices:
      - /dev/ttyACM0
    volumes:
      - ./data:/data
      - ./config:/boot  
      - ./params:/home/pi/parameters
      - ${SCRIPTS_PATH}:/home/pi/scripts
      - ${CREDENTIALS_PATH}:/home/pi/.aws/credentials
  MQTTbroker:
    image: eclipse-mosquitto:1.6.13
    restart: always
    ports:
      - "1883:1883"
    networks:
      - node-red-net

#volumes:
#  node-red-data:
networks:
  node-red-net:
