################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    build: .
    image: picroscope-hub-node-red:latest
#    environment:
#      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data:/data
      - ./config:/boot  
      - ./params:/home/pi/parameters
      - ~/.aws/credentials:/home/pi/.aws/credentials
  MQTTbroker:
    image: eclipse-mosquitto:1.6.13
#    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - node-red-net

#volumes:
#  node-red-data:
networks:
  node-red-net:
